language: perl6

os:
  - linux
  - osx

perl6:
  - 2017.03
  - latest

before_install:
  - echo $TRAVIS_OS_NAME

install:
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install Test::META
  - zef build .

before_script:
  # Install ncurses shared library on Linux/Debian using aptitude
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libncurses5 ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo apt-get install libncurses5 ; fi

script:
    - AUTHOR_TESTING=1 prove -ve "perl6 -Ilib"
    - zef install .
